[package]
name = "gnutella"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.11"
prost-types = "0.11"
rand = "0.3.14"
hex="0.4"
once_cell = "1.18.0"

[build-dependencies]
prost-build = "0.11"
